# Generated by Django 5.2.11 on 2026-02-10 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='fitness_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.fitnessclass'),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='fitness_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.fitnessclass'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='fitness_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='classes.fitnessclass'),
        ),
        migrations.AlterUniqueTogether(
            name='classbooking',
            unique_together={('user', 'fitness_class')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'fitness_class', 'date')},
        ),
    ]
